name: culture
description: A music reviewing app for mobile and web.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  confetti: ^0.7.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.4
  flutter_rating_bar: ^4.0.1
  go_router: ^7.0.1
  http: ^1.0.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hooks_riverpod: ^2.3.6

flutter:  
  uses-material-design: true   
  assets:   
    - assets/genreImages/
