// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWqr3PCes4v2XK0jZdhnA8X6dG4GdJHpw',
    appId: '1:415857317299:web:bc9dbd0293ee1d76de67c6',
    messagingSenderId: '415857317299',
    projectId: 'culture556',
    authDomain: 'culture556.firebaseapp.com',
    storageBucket: 'culture556.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6FuU2_mGbN9yT1T2Ga0pasi3a3TKyfo',
    appId: '1:415857317299:android:7ec999dc0798e061de67c6',
    messagingSenderId: '415857317299',
    projectId: 'culture556',
    storageBucket: 'culture556.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuK9yuFs-YW2oLlBmz-ZV_akNWQFlUUCM',
    appId: '1:415857317299:ios:a86a08d714cb8943de67c6',
    messagingSenderId: '415857317299',
    projectId: 'culture556',
    storageBucket: 'culture556.appspot.com',
    iosClientId: '415857317299-q67ov7rf28o8o59ifrab7ejqtnqdhj3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.culture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuK9yuFs-YW2oLlBmz-ZV_akNWQFlUUCM',
    appId: '1:415857317299:ios:a86a08d714cb8943de67c6',
    messagingSenderId: '415857317299',
    projectId: 'culture556',
    storageBucket: 'culture556.appspot.com',
    iosClientId: '415857317299-q67ov7rf28o8o59ifrab7ejqtnqdhj3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.culture',
  );
}
